reneos/acornr

app/models/booking.rb, app/models/space.rb, app/models/user.rb
Added associations and validations to users/bookings/spaces. Created and tested seed file
=> update model associations and validations, seed database

app/models/booking.rb
Created a booking validation to check whether there are any other existing bookings for that space that overlap with the start/end and for whether the start date is before the end date
=> Update booking validations

config/routes.rb
Completing routes, please check
=> Completing routes, please check

db/seeds.rb
updated seed to also create bookings of various dates for random spaces. Also ensures that bookings on spaces are not made by the host of the space
=> update seed to include bookings

app/controllers/bookings_controller.rb, app/controllers/dashboard_controller.rb, app/controllers/spaces_controller.rb, test/controllers/bookings_controller_test.rb, test/controllers/dashboard_controller_test.rb, test/controllers/spaces_controller_test.rb
Created controllers for spaces, bookings, dashboard
=> create controllers for spaces, bookings, dashboard

app/controllers/spaces_controller.rb
Completed spaces controller, please double check
=> Completed spaces controller

app/controllers/bookings_controller.rb
=> creating booking controller

Gemfile, Gemfile.lock, app/controllers/application_controller.rb, app/policies/application_policy.rb, app/policies/booking_policy.rb, app/policies/space_policy.rb, test/policies/booking_policy_test.rb, test/policies/space_policy_test.rb
Installed pundit and created basic policies for spaces and bookings
=> Implement authorization

app/controllers/spaces_controller.rb
added authorizations to spaces controller
=> authorize spaces in controller

app/controllers/bookings_controller.rb, app/controllers/dashboard_controller.rb
authorisation added please check
=> authorization added to booking controller

app/views/spaces/index.html.erb
Created files for spaces views
=> Created files for spaces views

app/controllers/pages_controller.rb, app/views/devise/confirmations/new.html.erb, app/views/devise/mailer/confirmation_instructions.html.erb, app/views/devise/mailer/email_changed.html.erb, app/views/devise/mailer/password_change.html.erb, app/views/devise/mailer/reset_password_instructions.html.erb, app/views/devise/mailer/unlock_instructions.html.erb, app/views/devise/passwords/edit.html.erb, app/views/devise/passwords/new.html.erb, app/views/devise/registrations/edit.html.erb, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/devise/shared/_error_messages.html.erb, app/views/devise/shared/_links.html.erb, app/views/devise/unlocks/new.html.erb, app/views/layouts/application.html.erb, app/views/shared/_flashes.html.erb, config/environments/development.rb
Create devise views, add alert flashes to layout, update devise config, whitelist homepage
=> Update devise config

app/assets/stylesheets/config/_fonts.scss
=> added two main fonts to fonts.scss

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_index.scss, app/controllers/application_controller.rb, app/views/spaces/_form.html.erb, app/views/spaces/index.html.erb, app/views/spaces/new.html.erb, app/views/spaces/show.html.erb
Added path links to index and show. Created form to create new space. Added some styling as well.
=> Added functionality to views

db/migrate/20200519033451_add_approved_to_bookings.rb, db/schema.rb
default is false for new bookings
=> add default approval to bookings

app/views/spaces/show.html.erb
fix missing @ for space show page
=> fix missing @

app/assets/stylesheets/components/_navbar.scss
=> Changed font colour on the nav bar

app/views/spaces/_form.html.erb, app/views/spaces/new.html.erb
=> create space form centered

app/assets/stylesheets/components/_navbar.scss, app/views/shared/_navbar.html.erb
Please review my code, current user email address has been added.
=> deleted home and replaced with current user email

app/assets/stylesheets/components/_card.scss, app/controllers/spaces_controller.rb, app/views/layouts/application.html.erb, app/views/spaces/index.html.erb
=> Made index page look prettier

app/assets/stylesheets/config/_fonts.scss
=> new font changed

app/controllers/bookings_controller.rb, app/controllers/spaces_controller.rb, app/policies/booking_policy.rb, app/views/shared/_navbar.html.erb, app/views/spaces/_form.html.erb, app/views/spaces/show.html.erb
=> Added booking logic to spaces

app/assets/stylesheets/pages/_home.scss, app/controllers/pages_controller.rb, app/views/layouts/application.html.erb, app/views/pages/home.html.erb
Made home page prettier and added sample spaces
=> Polished home page view and added sample spaces

Gemfile, Gemfile.lock, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_space-card.scss, app/controllers/spaces_controller.rb, app/models/space.rb, app/views/dashboard/index.html.erb, app/views/spaces/_form.html.erb, app/views/spaces/_space-card.html.erb, app/views/spaces/show.html.erb, config/environments/development.rb, config/environments/production.rb, config/storage.yml, db/migrate/20200520013558_create_active_storage_tables.active_storage.rb, db/schema.rb, db/seeds.rb
Added active storage and implemented displaying of a Space's attached image
=> add active storage and display attached image

app/views/shared/_navbar.html.erb
Added link between dashboard and navbar
=> Added link between dashboard and navbar

app/controllers/bookings_controller.rb, app/models/booking.rb, app/views/dashboard/_booking-card.html.erb, app/views/spaces/show.html.erb, db/migrate/20200520020641_add_message_to_bookings.rb, db/schema.rb
Please check the code, booking form changed and migration created
=> added message to booking form

app/views/spaces/show.html.erb, db/schema.rb
=> syntax fixed

app/assets/stylesheets/config/_bootstrap_variables.scss, app/views/dashboard/_booking-card.html.erb, db/schema.rb, db/seeds.rb
create seed for bookings w messages and add message display to dashboard
=> create seed for bookings w messages and add message display to dashboard

app/assets/stylesheets/pages/_index.scss, app/assets/stylesheets/pages/_show.scss, app/controllers/bookings_controller.rb, app/controllers/spaces_controller.rb, app/views/pages/home.html.erb, app/views/spaces/show.html.erb
- add flash notice to successful bookings/spaces creation
- add jumbotron to space show page and move form to the side
- change home page gradient
- fix date string on dashboard booking card
=> Update space view layout

app/assets/stylesheets/components/_space-card.scss, app/assets/stylesheets/pages/_home.scss, app/views/layouts/application.html.erb, app/views/pages/home.html.erb, app/views/spaces/_space-card.html.erb
- make card clickable
- keep footer on bottom
- make header text larger and more legible against  bg
- add nonfunctional search bar
- make address on space card smaller
=> layout tweaks

app/assets/stylesheets/components/_space-card.scss, app/assets/stylesheets/pages/_show.scss, app/views/spaces/show.html.erb, db/schema.rb
- increased font size for address
- increased banner height so address won't be hidden behind description
=> Adjusted space banner

app/controllers/bookings_controller.rb, app/controllers/dashboard_controller.rb, app/models/booking.rb, app/policies/booking_policy.rb, app/views/dashboard/_booking-card.html.erb, config/routes.rb, db/migrate/20200521002313_remove_date_range_from_bookings.rb, db/migrate/20200521023623_add_rejected_to_bookings.rb, db/schema.rb
- Created new rejected column (need to db:migrate)
- Added accept/decline actions to host-side dashboard
- Added accept/decline pills
- Accept/Decline links will disappear after accepted/declined
- Created flash messages
=> Host-side dashboard

app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_navs.scss, app/views/dashboard/_host_bookings.html.erb, app/views/dashboard/_host_spaces.html.erb, app/views/dashboard/_renter_bookings.html.erb, app/views/dashboard/index.html.erb
=> Added navs to dashboard

app/assets/stylesheets/components/_navbar.scss, app/views/dashboard/index.html.erb, app/views/shared/_navbar.html.erb
- Found out how to remove the glove
=> Removed pointer from avatar

app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_simple_form.scss, app/views/spaces/_form.html.erb
=> New form create

app/assets/stylesheets/components/_navbar.scss, app/assets/stylesheets/components/_simple_form.scss, db/schema.rb
=> Added style to navbar

app/assets/stylesheets/components/_simple_form.scss, app/javascript/packs/application.js, app/javascript/plugins/init_fileinput.js, app/javascript/plugins/init_litepicker.js, app/views/dashboard/_booking-card.html.erb, app/views/spaces/_form.html.erb, app/views/spaces/_space-card.html.erb, app/views/spaces/index.html.erb, app/views/spaces/show.html.erb
- update upload file button
- show preview img of photo
=> New upload btn

app/assets/stylesheets/components/_banner.scss, app/assets/stylesheets/pages/_home.scss, app/assets/stylesheets/pages/_show.scss, app/javascript/plugins/init_litepicker.js, app/models/booking.rb, app/views/pages/home.html.erb, app/views/shared/_navbar.html.erb, app/views/spaces/index.html.erb
- remove underline from price on index map page
- add spacing to header on home page
- make header text opaque on jumbotron
- update price calculator to properly say "day" when it's 1 day
=> tweak layout

app/views/shared/_navbar.html.erb
=> add logout
